<a href="https://colab.research.google.com/github/devopsmeysam/Machine-Learning-Code/blob/master/Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a constant tensor (2,2) which is essentially an array of array. Explore different properties of x.

In [ ]:
import tensorflow as tf
#print(tf.__version__)
#help(tf)
#help(tf.keras)
x=tf.constant([[5,2],[1,3]])
#x
print(x)
#x.numpy()
#x.dtype
#x.shape
print("\n")
x.backing_device

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)




'/job:localhost/replica:0/task:0/device:CPU:0'

Create a two-dimensional array with TensorFlow, using the "ones" function:

In [ ]:
import tensorflow as tf
tf.ones(shape=(5,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

Create a two-dimensional array with TensorFlow, using the "zeros" function:

In [ ]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Create a two-dimensional array with TensorFlow, using the "random" function:

In [ ]:
tf.random.normal(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.514782  , -0.10240368, -0.04734909, -2.4316142 ],
       [-0.8908117 , -0.0492361 , -0.70011795, -0.03275777],
       [-0.66164464,  0.9805981 , -0.77149636,  0.02135159]],
      dtype=float32)>

Now, create another two-dimensional array, but this time with a mean of 5 and a standard deviation of 3:

In [ ]:
tf.random.normal(shape=(2,3),mean =5 , stddev=3)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5.025781 , 4.3081846, 4.065384 ],
       [6.9249125, 7.2459483, 3.1603222]], dtype=float32)>

Create variable tensors with the corresponding methods :

In [3]:
import tensorflow as tf
xvar=tf.random.normal(shape=(3,3))
xvar

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.41206053, -0.32641292, -0.20028466],
       [ 0.6876914 , -0.01278838, -0.43997365],
       [ 0.1969185 , -0.5883358 ,  0.2978274 ]], dtype=float32)>

In [5]:
a=tf.Variable(xvar)
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.41206053, -0.32641292, -0.20028466],
       [ 0.6876914 , -0.01278838, -0.43997365],
       [ 0.1969185 , -0.5883358 ,  0.2978274 ]], dtype=float32)>

In [6]:
a.assign(tf.random.normal(shape=(3,3)))

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[ 0.07001999, -0.87092555,  0.18629777],
       [-0.9532621 , -1.0346274 ,  0.6129679 ],
       [-0.17073452,  0.97113585,  0.44412202]], dtype=float32)>

In [8]:
xvar_t_add=tf.random.normal(shape=(3,3))
xvar_t_add

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.13417143, -0.4249585 ,  1.1207068 ],
       [ 0.96420425,  1.2056038 , -0.7520308 ],
       [ 0.34190425,  1.3119246 , -2.401625  ]], dtype=float32)>

In [9]:
a.assign_add(xvar_t_add)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[ 0.20419142, -1.295884  ,  1.3070046 ],
       [ 0.01094216,  0.1709764 , -0.13906288],
       [ 0.17116973,  2.2830606 , -1.9575028 ]], dtype=float32)>

In [10]:
a.assign_sub(xvar_t_add)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[ 0.07001999, -0.87092555,  0.18629777],
       [-0.9532621 , -1.0346274 ,  0.6129679 ],
       [-0.17073452,  0.971136  ,  0.44412208]], dtype=float32)>

New Operations:

In [11]:
new_value=tf.random.normal(shape=(3,3))
new_value

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.4486506 , -0.9093869 , -0.01833314],
       [-0.6150971 ,  0.804267  ,  0.40893623],
       [ 0.15566841,  0.5909714 ,  1.7716775 ]], dtype=float32)>

In [12]:
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.07001999, -0.87092555,  0.18629777],
       [-0.9532621 , -1.0346274 ,  0.6129679 ],
       [-0.17073452,  0.971136  ,  0.44412208]], dtype=float32)>

In [13]:
a.assign_add(new_value)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[-1.3786306 , -1.7803124 ,  0.16796464],
       [-1.5683591 , -0.23036045,  1.0219041 ],
       [-0.01506612,  1.5621073 ,  2.2157996 ]], dtype=float32)>

In [14]:
b=tf.random.normal(shape=(3,3))
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3282992 , -0.92686814,  0.16322441],
       [-0.19672227,  0.50247   , -0.1393468 ],
       [-1.4557648 ,  0.41720596, -0.39894986]], dtype=float32)>

In [15]:
c=a+b
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.05033147, -2.7071805 ,  0.33118904],
       [-1.7650814 ,  0.27210957,  0.88255733],
       [-1.4708309 ,  1.9793133 ,  1.8168497 ]], dtype=float32)>

In [16]:
d=tf.square(c)
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.5332572e-03, 7.3288264e+00, 1.0968618e-01],
       [3.1155124e+00, 7.4043617e-02, 7.7890742e-01],
       [2.1633437e+00, 3.9176810e+00, 3.3009429e+00]], dtype=float32)>

In [17]:
e=tf.exp(c)
e

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.95091414, 0.06672467, 1.3926231 ],
       [0.17117286, 1.3127308 , 2.4170732 ],
       [0.22973451, 7.2377706 , 6.152446  ]], dtype=float32)>

In [18]:
with tf.GradientTape() as tape:
    tape.watch(a)
    f=tf.sqrt(tf.square(a)+tf.square(b))
    df_da=tape.gradient(f,a)
    print(df_da)

tf.Tensor(
[[-0.72012997 -0.8869912   0.71715397]
 [-0.99222505 -0.41674694  0.9908307 ]
 [-0.01034873  0.96613574  0.98417515]], shape=(3, 3), dtype=float32)


Functional API:

In [29]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
#--------------------
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
#--------------------
model = tf.keras.models.Sequential([
tf.keras.layers.Flatten(input_shape=(28, 28)),
tf.keras.layers.Dense(128, activation='relu'),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10, activation='softmax')
])
#--------------------
model.compile(optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])
#--------------------
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

Epoch 1/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2948 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1420 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.1079 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0878 - accuracy: 0.9732
Epoch 5/5
313/313 [==============================] - 1s 3ms/step - loss: 0.0717 - accuracy: 0.9766


[0.07170568406581879, 0.9765999913215637]

KERAS:

In [39]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
#--------------------
inputs = keras.Input(shape=(784,)) #2^3*7^2
#--------------------
dense = layers.Dense(64, activation="relu")
x = dense(inputs)
#--------------------
y = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(10)(y)
#--------------------
model = keras.Model(inputs=inputs, outputs=outputs, name="mnist_model")
keras.utils.plot_model(model, r"my_first_model.png")
keras.utils.plot_model(model, r"my_first_model_with_shape_info.png", show_shapes=True)
#--------------------
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
#--------------------
x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255
#--------------------
model.compile(
loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
optimizer=keras.optimizers.RMSprop(),
metrics=["accuracy"])
#--------------------
history = model.fit(x_train, y_train, batch_size=64, epochs=2, validation_split=0.2)
#--------------------
test_scores = model.evaluate(x_test, y_test, verbose=2)
print("Test loss:", test_scores[0])
print("Test accuracy:", test_scores[1])
#--------------------
model.save(r"keras_model.mdl")
del model
# Recreate the exact same model purely from the file:
model2 = keras.models.load_model(r"keras_model.mdl")
model2.summary()

Epoch 1/2
750/750 [==============================] - 5s 6ms/step - loss: 0.3507 - accuracy: 0.9006 - val_loss: 0.1860 - val_accuracy: 0.9450
Epoch 2/2
750/750 [==============================] - 4s 6ms/step - loss: 0.1611 - accuracy: 0.9522 - val_loss: 0.1413 - val_accuracy: 0.9568
313/313 - 1s - loss: 0.1354 - accuracy: 0.9595 - 994ms/epoch - 3ms/step
Test loss: 0.13538767397403717
Test accuracy: 0.9595000147819519


Model: "mnist_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_10 (InputLayer)       [(None, 784)]             0         
                                                                 
 dense_27 (Dense)            (None, 64)                50240     
                                                                 
 dense_28 (Dense)            (None, 64)                4160      
                                                                 
 dense_29 (Dense)            (None, 10)                650       
                                                                 
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________
